services:
  app:
    build: .
    networks:
      - main
    depends:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .app.env
  redis:
    image: redis:alpine
  db:
    image: postgres
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .db.env
networks:
  main:
