[project]
name = "travel-agent-bot"
version = "1.0"
description = "Implementation of Travel Agent 3.0 by @samylovma"
authors = [
    {name = "Mikhail Samylov", email = "samylov-mikhail@yandex.ru"},
]
dependencies = [
    "python-telegram-bot>=21.0.1",
    "advanced-alchemy>=0.7.4",
]
requires-python = "==3.12.*"
readme = "README.md"


[project.optional-dependencies]
sqlite = [
    "aiosqlite>=0.20.0",
]
postgresql = [
    "asyncpg>=0.29.0",
]
[tool.pdm]
distribution = false
